#!/usr/bin/env bash
echo -e "Updating\n"

sudo apt-get update

echo -e "Installing UFW\n"

sudo apt-get install -y ufw

echo -e "configuring UFW...\n"

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable Fire Wall
sudo ufw enable

# Check ufw status
sudo ufw status verbose

echo -e "Process Completed.\n"


sudo apt -y update
sudo apt -y install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw show added
sudo ufw app list
sudo ufw enable
