#!/usr/bin/env bash
# /etc/ufw/before.rules

*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]

# Port forwarding from 8080 to 80
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

COMMIT

# rest of the file remains unchanged

